'use strict';

import React from 'react';
import LessonBase from './LessonBase';
import End from './Lesson1/_End.jsx';

export default new LessonBase([
    { page: <img src="/upload/templates/template1/Фото_1_1.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_1_1+.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_2_1.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_2_1+.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_3_1.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_3_1+.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_4_1.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_4_1+.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_4_2.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_5_1.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_5_2 +.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_5_2.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_6_1 +.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_6_1.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_7_1.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_7_2.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_7_3 +.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_7_3.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_8_1.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_8_2 +.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_8_2.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_9_1.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_9_2 +.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_9_2.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_10_1 +.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_10_1.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_11_1 +.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_11_1.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_11_1.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_12_1.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_12_2.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_12_2+.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_13_1.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_13_2.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_13_3.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_13_3+.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_Пример_1_1.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_Пример_1_2.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_Пример_2_1.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_Пример_2_2.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_Пример_3_1.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_Пример_3_2.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_Пример_4_1.jpg" /> },
    { page: <img src="/upload/templates/template1/Фото_Пример_4_2.jpg" /> },

    { page: End },
]);